### ISSUE TITLE
Evaluate Finesse Effectiveness using Generated Q&A

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/finesse-backend#38]
## Summary
Currently, there is a challenge as there is no established method for effectively testing the Finesse's performance. This poses a significant issue, as delivering an untested tool may lead to uncertainties regarding its functionality and reliability. The objective is to utilize the automatically generated questions and answers by finesse-data to assess the functionality of Finesse. The goal is to verify if Finesse returns the document among the top choices, establishing a quantification of the tool's efficiency.

## Tasks

- [ ] Create a testing script that integrate the generated Q&A data
  - [ ] Select a test function on a CLI interface
    - [ ] --evaluate-all, Test all the QnAs for a Finesse search
    - [ ] --qna-file, Test a specific QnA by inputing its file name
    - [ ] --question, Test a new question by inputing the question and the document title
  - [ ] Select the type of Finesse search to get lists of pages returned by Finesse on a CLI interface
    - [ ] --ai-lab, AI-Lab search
    - [ ] --azure, Azure search
    - [ ] --static, Static search
  - [ ] Compare the expected page in the QnAs with the response pages
  - [ ] Establish a reliability score for Finesse (potentially using LLM for evaluation)
  - [ ] Quantify Finesse's efficiency based on all the scores obtained and output on a CLI interface
- [ ] Validate if the question page is among the top response pages as expected, if not investigate and document possible causes.

### Argument evaluate-all example
```bash
$ finesse-test --evaluate-all --azure
Searching with Azure Search...

File: "qna_2023-12-08_15"
Question: "Quels sont les numéros de téléphone pour les demandes de renseignements du public?"
Reliability Score: 70%

File: "qna_2023-12-08_17"
Question: "Quels sont les contacts pour les demandes de renseignements du public?"
Reliability Score: 85%

...

Finesse Overall Efficiency: 77%
```

### Argument qna-file example
```bash
$ finesse-test --qna-file "qna_2023-12-08_41" --azure
Searching with Azure Search...

Pages returned:
1. Demandes de renseignements du public et des médias
2. 4.2 Matériel de multiplication de Rubus spp. des Pays-Bas ou de l'Allemagne
3. Pour les consommateurs

Expected Page: 3.9.2 En provenance de la zone continentale des États-Unis

Reliability Score: 0%
```
### Argument question example
```bash
$ finesse-test --question "Quels végétaux nécessitent un permis d'importation en provenance de la zone continentale des États-Unis?" --azure
Searching with Azure Search...

Pages returned:
1. Demandes de renseignements du public et des médias
2. 4.2 Matériel de multiplication de Rubus spp. des Pays-Bas ou de l'Allemagne
3. Pour les consommateurs

Expected Page: 3.9.2 En provenance de la zone continentale des États-Unis

Reliability Score: 0%
```

## Acceptance Criteria

- Finesse successfully incorporates questions generated by the finesse-data repository.
- The testing tool effectively integrates with Finesse
- Finesse's efficiency is quantified based on the accurate positioning of the correct document in the provided list.
- In case of discrepancies, a detailed investigation and documentation of potential causes are provided.
- The testing tool documentation includes clear steps for integration, execution, and validation.

**Comment by rngadam** [comment]
Some definitions as the description needs to be reworked:

https://en.wikipedia.org/wiki/List_of_system_quality_attributes

* Effectiveness or effectivity: the capability of producing a desired result or the ability to produce desired output. When something is deemed effective, it means it has an intended or expected outcome
* Efficiency: The extent to which a resource is used for the intended purpose; the ratio of useful work to energy expended. 
* Reliability: a software's ability to function, given environmental conditions, for a particular amount of time
* Features vs Functionality: Features are the “tools” you use within a system to complete a set of tasks or actions. Functionality is how those features actually work to provide you with a desired outcome.

Also:

* Acceptance criteria: defined as the conditions that must be satisfied for a product, user story, or increment of work to be accepted.   Acceptance criteria are either met or not met; they're never only partially fulfilled. Acceptance criteria do not focus on “how” a solution is reached or “how” something is made. Instead, they illuminate the “what” of the work you are doing.

**Comment by leejaeka** [comment]
[Added llamindex test accuracy result](https://136gc-my.sharepoint.com/:x:/r/personal/tony_lee_inspection_gc_ca/Documents/llamaindex%20test%201.xlsx?d=wfd88b783ae024bd7a257a73ac2ddd092&csf=1&web=1&e=e9nyXv) following 1-(position of target doc/20) formula. 
[Updated notebook](https://github.com/ai-cfia/llamaindex-db/pull/3) with code that tests accuracy
