### ISSUE TITLE
llamaindex LLM output

### ISSUE THREAD

**Issue by leejaeka** [ai-cfia/finesse-backend#41]
llamaindex has two outputs 1. Top k number of relative documents in order 2. Answer generated by llm after reading query and relative documents from (1) [llamaindex high level concept](https://docs.llamaindex.ai/en/stable/getting_started/concepts.html) Currently, second part of llamaindex has no concrete plan. The goal is to 
return accurate summary of documents to save user's time and effort.

## Tasks
- [ ] Testing required to compare with Louis capabilities as it may be overlapping  
- [ ] Ideas in possible integrations with Finesse

## Acceptance Criteria
- [ ] To be determined

**Comment by rngadam** [comment]
don't forget to set the "Projects" field

**Comment by ibrahim-kabir** [comment]
This feature has been implemented in this [branch](https://github.com/orgs/ai-cfia/projects/9/views/8?pane=issue&itemId=52258045)
