### ISSUE TITLE
Enhance Finesse Benchmark Tool with Cost Estimation and Data Visualization Features

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/finesse-backend#46]
> [!NOTE]
> This Issue will be moved in a new repository once the [Incorporate Finesse Benchmarking Tool](https://github.com/ai-cfia/finesse-backend/pull/39) PR will be merged

## Summary
The finesse benchmark tool currently provides an accuracy score and request time for each JSON file. However, it lacks the capability to generate cost estimates. This tool is responsible for comparing different search engines to discern the best from the worst, and one decisive factor is inevitably the cost incurred by using a tool. Additionally, the tool saves tests locally, and not all the test data is exported to CSV and MD files, such as the entirety of search engine responses. This can result in loss of results and traceability. Finally, it would be beneficial to add a data visualizer such as a graph. Therefore, we are enhancing this tool with the locust-dashboard, which enables us to implement all the aforementioned features.

## Tasks:
- [ ] Integrate cost estimation feature into finesse benchmark tool.
- [ ] Create a schema on Datahub 
- [ ] Save all the test data on the PostgreSQL table
- [ ] Create Jupyter Notebooks to save data on md and csv file
- [ ] Implement a data visualizer on the locust-dashboard, such as a graph, to enhance data analysis capabilities.

## Acceptance Criteria
- The finesse benchmark tool successfully generates cost estimates for each search engine.
- All test data, including search engine responses, are saved on datahub
- The implemented data visualizer effectively presents the benchmark results, enhancing data analysis capabilities.
