### ISSUE TITLE
Integrate llamaindex in finesse-backend

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-backend#51]
## Description:
We need to integrate our new index created using llamaindex into our finesse-backend. Use the `ailab-llama-search` package, which is available for installation via pip in `llamaindex-db`. 

## Tasks:
- [ ] Integrate `ailab-llama-search` package.
- [ ] Update the backend configuration to use the new index from `llamaindex-db`.
- [ ] Create a new endpoint for it.
- [ ] Update tests.
- [ ] Update docs.

## Acceptance Criteria:
- Searches can be made on the new index with no errors.
- All tests confirm the new index's successful integration.
- Documentation is updated.

**Comment by rngadam** [comment]
I see that the naming from the description is a bit inconsistent, with llama being used. shall we stick to llamaindex everywhere as that's the name of the product.
