### ISSUE TITLE
Add Endpoint for File Name Retrieval from finesse-data in finesse-backend

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-backend#9]
Currenty, `finesse-frontend` fetches file names directly from the `finesse-data` repository. We want to remove specific source knowledge from the frontend to promote flexibility. A solution is to introduce a new endpoint in `finesse-backend` to fetch file names from `finesse-data`.

### Tasks:
- [x] Create API endpoint structure.
- [x] Develop functionality for retrieving file names.
- [x] Write unit tests.
- [x] Update API documentation.

### Acceptance Criteria:
- Endpoint returns file names from `finesse-data`.
- Unit tests.
- Documentation is updated.

**Comment by rngadam** [comment]
Can you explain the Why in your description? What is the purpose?

**Comment by k-allagbe** [comment]
> Can you explain the Why in your description? What is the purpose?

Done. This is just to remove the source knowledge from the frontend. Currently, the frontend bypasses the backend to access `finesse-data` which we can consider a source.

**Comment by rngadam** [comment]
I still find this confusing because it doesn't really relate to the purpose of the backend (search). I think what we may want to express here is a general service to fetch sample queries (which could be a good service, for example returning top queries).

**Comment by rngadam** [comment]
Not sure I can write a better spec for this feature than you could.

Suggested queries; API returns list of example queries.

For now, as we're cold starting search, we can just return the list of filenames turned into title from finesse-data (matching what we use for testing). Eventually, this could be dynamically determined from recent popular searches (personalized to user profile).

Separately, just to remind us, the reason why the frontend accesses finesse-data directly is for frontend static testing without the backend which means the implementation in the frontend i probably something we want to keep in.

**Comment by k-allagbe** [comment]
> Not sure I can write a better spec for this feature than you could.
> 
> Suggested queries; API returns list of example queries.
> 
> For now, as we're cold starting search, we can just return the list of filenames turned into title from finesse-data (matching what we use for testing). Eventually, this could be dynamically determined from recent popular searches (personalized to user profile).
> 
> Separately, just to remind us, the reason why the frontend accesses finesse-data directly is for frontend static testing without the backend which means the implementation in the frontend i probably something we want to keep in.

Sounds good.
